version: "3.9"

services:
  frontend:
    image: nafis3507/three-tier-frontend:${TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: nafis3507/three-tier-backend:${TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=appdb
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppass
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
