services:
  frontend:
    image: nafis38/three-tier-frontend:${TAG:-latest}
    ports: ["80:80"]
    depends_on: [backend]
    environment:
      - API_BASE_URL=http://backend:8080

  backend:
    image:  nafis38/three-tier-backend:${TAG:-latest}
    ports: ["8080:8080"]
    depends_on: [db]
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=appdb

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
      - POSTGRES_DB=appdb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
