name: CD - Deploy to VM

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            APP_DIR="/home/ubuntu/lemp-containers"

            echo "➡ Checking for application directory..."
            if [ ! -d "$APP_DIR/.git" ]; then
              echo "🟡 Directory not found or not a git repo. Cloning fresh..."
              rm -rf "$APP_DIR"
              mkdir -p "$APP_DIR"
              git clone https://github.com/zaryabnafis-prog/lemp-containers.git "$APP_DIR"
            else
              echo "🟢 Existing repo found. Pulling latest changes..."
              cd "$APP_DIR"
              git reset --hard
              git clean -fd
              git pull
            fi

            cd "$APP_DIR"
            export TAG=latest

            echo "🐳 Starting Docker deployment..."
            docker compose -f docker-compose.prod.yml pull
