name: CD - Deploy to VM

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd /home/ubuntu

            
            if [ ! -d "lemp-containers" ]; then
              git clone https://github.com/zaryabnafis-prog/lemp-containers.git
            else
              cd lemp-containers && git pull
            fi

            cd lemp-containers
            export TAG=latest

            
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans --build
            docker image prune -f
