name: CD - Deploy to VM
on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Pull images & restart via docker compose
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_APP_DIR: ${{ secrets.REMOTE_APP_DIR }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
          set -e
          cd "$REMOTE_APP_DIR"
          export TAG=latest
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
          EOF
