name: CD - Deploy LEMP App to VM

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "=== Starting deploy on $(hostname) ==="
            cd /home/ubuntu/
            git clone https://github.com/zaryabnafis-prog/lemp-containers.git
            cd /home/ubuntu/lemp-containers || exit 1

            echo "--- Checking Git status ---"
            git status || exit 1

            echo "--- Resetting repo to main ---"
            git fetch origin main || exit 1
            git reset --hard origin/main || exit 1

            echo "--- Pulling latest code ---"
            git pull origin main || exit 1

            echo "--- Stopping and removing old containers ---"
            docker compose -f docker-compose.prod.yml down || true

            echo "--- Building and starting containers ---"
            docker compose -f docker-compose.prod.yml up -d --build --pull=always || exit 1

            echo "✅ Deploy completed successfully!"
