name: CI - Build & Push Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/three-tier-frontend:${{ env.IMAGE_TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/three-tier-frontend:latest

      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/three-tier-backend:${{ env.IMAGE_TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/three-tier-backend:latest
